name: Container

on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:19-alpine3.16
    steps:
      - name: Log node version
        run: node -v
      - name: Step with Docker
        uses: docker://node:16-alpine3.16
        with:
          entrypoint: '/bin/echo'  # path to executable file
          args: 'Hello World'
      - name: Log node version 2
        uses: docker://node:16-alpine3.16
        with:
          entrypoint: '/usr/local/bin/node'
          args: -v
      - name: Checkout your commit
        uses: actions/checkout@v1
      - name: Run a script
        uses: docker://node:16-alpine3.16
        with:
          entrypoint: ./script.sh
          args: "Some string"
#  node-docker:
#    runs-on: ubuntu-latest
#    services:
#      app:
#        image: alialaa17/node-api
#        ports:
#          - 3001:3000
#      mongo:
#        image: mongo
#        ports:
#          - "27017:27017"
#    steps:
#      - name: POST a user
#        run: "curl -X POST http://localhost:3001/api/user -H 'Content-Type: application/json' -d '{\"username\": \"hello\", \"address\": \"dwded\"}'"
#      - name: GET all users
#        run: curl http://localhost:3001/api/users